//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapaAction
    {
        public int Id { get; set; }
        public Nullable<int> CapaId { get; set; }
        public Nullable<int> Who { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> ExtensionDate { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Signature { get; set; }
        public string Type { get; set; }
        public string SiteId { get; set; }
    }
}
