//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EnscoIrmaEntities : DbContext
    {
        public EnscoIrmaEntities()
            : base("name=EnscoIrmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<POB_SummaryView> POB_SummaryView { get; set; }
        public virtual DbSet<Master_ActionStatus> Master_ActionStatus { get; set; }
        public virtual DbSet<Master_Application> Master_Application { get; set; }
        public virtual DbSet<Master_BusinessUnit> Master_BusinessUnit { get; set; }
        public virtual DbSet<Master_ChangeHistory> Master_ChangeHistory { get; set; }
        public virtual DbSet<Master_Company> Master_Company { get; set; }
        public virtual DbSet<Master_CorpPersonnelRelation> Master_CorpPersonnelRelation { get; set; }
        public virtual DbSet<Master_Gender> Master_Gender { get; set; }
        public virtual DbSet<Master_MaritalStatus> Master_MaritalStatus { get; set; }
        public virtual DbSet<Master_Nationality> Master_Nationality { get; set; }
        public virtual DbSet<Master_PassportReconciliation> Master_PassportReconciliation { get; set; }
        public virtual DbSet<Master_Relationship> Master_Relationship { get; set; }
        public virtual DbSet<Master_RigAssetRelation> Master_RigAssetRelation { get; set; }
        public virtual DbSet<Master_RigPersonnelRelation> Master_RigPersonnelRelation { get; set; }
        public virtual DbSet<Master_Scheduler> Master_Scheduler { get; set; }
        public virtual DbSet<Master_UserGovtIdSubType> Master_UserGovtIdSubType { get; set; }
        public virtual DbSet<Master_UserGovtIdType> Master_UserGovtIdType { get; set; }
        public virtual DbSet<Master_UserRecords> Master_UserRecords { get; set; }
        public virtual DbSet<Master_UserRoles> Master_UserRoles { get; set; }
        public virtual DbSet<Master_UserStatus> Master_UserStatus { get; set; }
        public virtual DbSet<Master_UserType> Master_UserType { get; set; }
        public virtual DbSet<POB_Admin> POB_Admin { get; set; }
        public virtual DbSet<POB_ChangeHistory> POB_ChangeHistory { get; set; }
        public virtual DbSet<POB_CrewChange> POB_CrewChange { get; set; }
        public virtual DbSet<POB_CrewFlight> POB_CrewFlight { get; set; }
        public virtual DbSet<POB_CrewFlightPob> POB_CrewFlightPob { get; set; }
        public virtual DbSet<POB_Emails> POB_Emails { get; set; }
        public virtual DbSet<POB_EmergencyTeam> POB_EmergencyTeam { get; set; }
        public virtual DbSet<POB_EmergencyTeamMembers> POB_EmergencyTeamMembers { get; set; }
        public virtual DbSet<POB_FlightParkingLot> POB_FlightParkingLot { get; set; }
        public virtual DbSet<POB_LifeBoat> POB_LifeBoat { get; set; }
        public virtual DbSet<POB_MusterStation> POB_MusterStation { get; set; }
        public virtual DbSet<POB_PersonnelType> POB_PersonnelType { get; set; }
        public virtual DbSet<POB_PobStatus> POB_PobStatus { get; set; }
        public virtual DbSet<POB_RigCrew> POB_RigCrew { get; set; }
        public virtual DbSet<POB_RigFieldVisibility> POB_RigFieldVisibility { get; set; }
        public virtual DbSet<POB_RigPersonnelHistory> POB_RigPersonnelHistory { get; set; }
        public virtual DbSet<POB_RigRequirementCompliance> POB_RigRequirementCompliance { get; set; }
        public virtual DbSet<POB_RigRequirements> POB_RigRequirements { get; set; }
        public virtual DbSet<POB_RigSubRequirement> POB_RigSubRequirement { get; set; }
        public virtual DbSet<POB_Room> POB_Room { get; set; }
        public virtual DbSet<POB_RoomBed> POB_RoomBed { get; set; }
        public virtual DbSet<POB_RotationDays> POB_RotationDays { get; set; }
        public virtual DbSet<POB_ScheduleType> POB_ScheduleType { get; set; }
        public virtual DbSet<POB_TeamType> POB_TeamType { get; set; }
        public virtual DbSet<POB_Tour> POB_Tour { get; set; }
        public virtual DbSet<POB_TourChange> POB_TourChange { get; set; }
        public virtual DbSet<POB_Banksman> POB_Banksman { get; set; }
        public virtual DbSet<POB_CavReason> POB_CavReason { get; set; }
        public virtual DbSet<Master_PassportReconciliationView> Master_PassportReconciliationView { get; set; }
        public virtual DbSet<Master_UserLookupView> Master_UserLookupView { get; set; }
        public virtual DbSet<Master_UserNonADLookupView> Master_UserNonADLookupView { get; set; }
        public virtual DbSet<Master_UserOnboardLookupView> Master_UserOnboardLookupView { get; set; }
        public virtual DbSet<POB_AdminView> POB_AdminView { get; set; }
        public virtual DbSet<POB_BatchOffboardView> POB_BatchOffboardView { get; set; }
        public virtual DbSet<POB_BatchOnboardView> POB_BatchOnboardView { get; set; }
        public virtual DbSet<POB_CrewArrivalDepartureLogView> POB_CrewArrivalDepartureLogView { get; set; }
        public virtual DbSet<POB_CrewBreakdownView> POB_CrewBreakdownView { get; set; }
        public virtual DbSet<POB_CrewChangeApproverView> POB_CrewChangeApproverView { get; set; }
        public virtual DbSet<POB_CrewChangeFlights> POB_CrewChangeFlights { get; set; }
        public virtual DbSet<POB_CrewFlightManifestView> POB_CrewFlightManifestView { get; set; }
        public virtual DbSet<POB_CrewPobView> POB_CrewPobView { get; set; }
        public virtual DbSet<POB_CrewSearchView> POB_CrewSearchView { get; set; }
        public virtual DbSet<POB_CurrentPobView> POB_CurrentPobView { get; set; }
        public virtual DbSet<POB_EmergencyTeamReportView> POB_EmergencyTeamReportView { get; set; }
        public virtual DbSet<POB_FlightArrivalDepartureLogView> POB_FlightArrivalDepartureLogView { get; set; }
        public virtual DbSet<POB_FlightManifestUnassigned> POB_FlightManifestUnassigned { get; set; }
        public virtual DbSet<POB_FlightParkingLotView> POB_FlightParkingLotView { get; set; }
        public virtual DbSet<POB_FlightPobView> POB_FlightPobView { get; set; }
        public virtual DbSet<POB_History> POB_History { get; set; }
        public virtual DbSet<POB_LifeBoatComplianceView> POB_LifeBoatComplianceView { get; set; }
        public virtual DbSet<POB_LifeBoatRosterListView> POB_LifeBoatRosterListView { get; set; }
        public virtual DbSet<POB_OnOffBoardReportView> POB_OnOffBoardReportView { get; set; }
        public virtual DbSet<POB_RigComplianceUserView> POB_RigComplianceUserView { get; set; }
        public virtual DbSet<POB_RigComplianceView> POB_RigComplianceView { get; set; }
        public virtual DbSet<POB_RigPersonnelDB> POB_RigPersonnelDB { get; set; }
        public virtual DbSet<POB_RigPersonnelHistoryView> POB_RigPersonnelHistoryView { get; set; }
        public virtual DbSet<POB_RoomBedView> POB_RoomBedView { get; set; }
        public virtual DbSet<POB_RosterByLifeBoatView> POB_RosterByLifeBoatView { get; set; }
        public virtual DbSet<POB_RosterByMusterStationVIew> POB_RosterByMusterStationVIew { get; set; }
        public virtual DbSet<POB_RosterSignInView> POB_RosterSignInView { get; set; }
        public virtual DbSet<POB_SummaryByCompanyTypeView> POB_SummaryByCompanyTypeView { get; set; }
        public virtual DbSet<POB_SummaryOtherView> POB_SummaryOtherView { get; set; }
        public virtual DbSet<POB_TeamMemberView> POB_TeamMemberView { get; set; }
        public virtual DbSet<POB_TeamView> POB_TeamView { get; set; }
        public virtual DbSet<POB_TourMangementView> POB_TourMangementView { get; set; }
        public virtual DbSet<PobTeam> PobTeam { get; set; }
        public virtual DbSet<vw_Capa> vw_Capa { get; set; }
        public virtual DbSet<vw_EiIsolation> vw_EiIsolation { get; set; }
        public virtual DbSet<vw_Task> vw_Task { get; set; }
        public virtual DbSet<Lock> Lock { get; set; }
        public virtual DbSet<JOB_PermitView> JOB_PermitView { get; set; }
        public virtual DbSet<JOB_SummaryView> JOB_SummaryView { get; set; }
        public virtual DbSet<Master_Position> Master_Position { get; set; }
        public virtual DbSet<Master_Approvals> Master_Approvals { get; set; }
        public virtual DbSet<Master_Client> Master_Client { get; set; }
        public virtual DbSet<Master_DesignatedPerson> Master_DesignatedPerson { get; set; }
        public virtual DbSet<Master_EnscoLocation> Master_EnscoLocation { get; set; }
        public virtual DbSet<Master_AssetType> Master_AssetType { get; set; }
        public virtual DbSet<OAP_LessonsLearnedOriginators> OAP_LessonsLearnedOriginators { get; set; }
        public virtual DbSet<Master_Department> Master_Department { get; set; }
        public virtual DbSet<Master_RigStatus> Master_RigStatus { get; set; }
        public virtual DbSet<OAP_LessonsLearnedType> OAP_LessonsLearnedType { get; set; }
        public virtual DbSet<Master_LocationMapping> Master_LocationMapping { get; set; }
        public virtual DbSet<Master_Location> Master_Location { get; set; }
        public virtual DbSet<Master_RigType> Master_RigType { get; set; }
        public virtual DbSet<Master_JobCode> Master_JobCode { get; set; }
        public virtual DbSet<Master_AdminPersonnel> Master_AdminPersonnel { get; set; }
        public virtual DbSet<vw_Master_Location> vw_Master_Location { get; set; }
        public virtual DbSet<Vw_OApChecklists> Vw_OApChecklists { get; set; }
        public virtual DbSet<OAP_Comment> OAP_Comment { get; set; }
        public virtual DbSet<Master_SharedAccount> Master_SharedAccount { get; set; }
        public virtual DbSet<POB_RigPersonnel> POB_RigPersonnel { get; set; }
        public virtual DbSet<PobList> PobList { get; set; }
        public virtual DbSet<POB_IndividualOnboardView> POB_IndividualOnboardView { get; set; }
        public virtual DbSet<TRN_CoursesSyncedToRig> TRN_CoursesSyncedToRig { get; set; }
        public virtual DbSet<vw_JobLookup> vw_JobLookup { get; set; }
        public virtual DbSet<Master_ActionType> Master_ActionType { get; set; }
        public virtual DbSet<Master_RootCause> Master_RootCause { get; set; }
        public virtual DbSet<vw_TaskCap> vw_TaskCap { get; set; }
        public virtual DbSet<vw_TaskTlc> vw_TaskTlc { get; set; }
        public virtual DbSet<OAP_LessonsLearned> OAP_LessonsLearned { get; set; }
        public virtual DbSet<Master_ControlHierarchy> Master_ControlHierarchy { get; set; }
        public virtual DbSet<Master_Criticality> Master_Criticality { get; set; }
        public virtual DbSet<CapaPlan> CapaPlan { get; set; }
        public virtual DbSet<CapaAction> CapaAction { get; set; }
        public virtual DbSet<vw_SharedAndCorpAccount> vw_SharedAndCorpAccount { get; set; }
        public virtual DbSet<vw_OpenCap> vw_OpenCap { get; set; }
        public virtual DbSet<vw_OpenTraining> vw_OpenTraining { get; set; }
        public virtual DbSet<vw_Topic> vw_Topic { get; set; }
        public virtual DbSet<vw_CapaPlanExecution> vw_CapaPlanExecution { get; set; }
        public virtual DbSet<vw_CapaLookup> vw_CapaLookup { get; set; }
        public virtual DbSet<IrmaCapa> IrmaCapa { get; set; }
        public virtual DbSet<AdminRole> AdminRole { get; set; }
        public virtual DbSet<Tbl_Identity> Tbl_Identity { get; set; }
        public virtual DbSet<vw_AdminCustom> vw_AdminCustom { get; set; }
        public virtual DbSet<Master_ApprovalVew> Master_ApprovalVew { get; set; }
        public virtual DbSet<Master_UserNotCrewOnboardLookupVIew> Master_UserNotCrewOnboardLookupVIew { get; set; }
        public virtual DbSet<Master_UserCrewOnboardLookupView> Master_UserCrewOnboardLookupView { get; set; }
        public virtual DbSet<vw_POB_RigPersonnel> vw_POB_RigPersonnel { get; set; }
        public virtual DbSet<vw_OpenJob> vw_OpenJob { get; set; }
        public virtual DbSet<vw_OpenEi> vw_OpenEi { get; set; }
        public virtual DbSet<vw_POB_RigPersonnelHistory> vw_POB_RigPersonnelHistory { get; set; }
        public virtual DbSet<IrmaCapaPlan> IrmaCapaPlan { get; set; }
        public virtual DbSet<SWA> SWA { get; set; }
        public virtual DbSet<WiLocal> WiLocal { get; set; }
        public virtual DbSet<vw_Job> vw_Job { get; set; }
        public virtual DbSet<Common_Attachments> Common_Attachments { get; set; }
        public virtual DbSet<Master_Rig> Master_Rig { get; set; }
        public virtual DbSet<Master_Users> Master_Users { get; set; }
        public virtual DbSet<CorpCapa> CorpCapa { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<Master_UserNotOnboardLookupVIew> Master_UserNotOnboardLookupVIew { get; set; }
        public virtual DbSet<OAP_Review> OAP_Review { get; set; }
    
        public virtual int CreatePassport(Nullable<int> rigId, Nullable<int> passportId)
        {
            var rigIdParameter = rigId.HasValue ?
                new ObjectParameter("RigId", rigId) :
                new ObjectParameter("RigId", typeof(int));
    
            var passportIdParameter = passportId.HasValue ?
                new ObjectParameter("PassportId", passportId) :
                new ObjectParameter("PassportId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreatePassport", rigIdParameter, passportIdParameter);
        }
    
        public virtual int GetAvailableBeds(Nullable<int> rigId, ObjectParameter returnValue)
        {
            var rigIdParameter = rigId.HasValue ?
                new ObjectParameter("RigId", rigId) :
                new ObjectParameter("RigId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAvailableBeds", rigIdParameter, returnValue);
        }
    
        public virtual int ChangeTourForTheDay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeTourForTheDay");
        }
    
        public virtual int UpdateAdminCustomValue(string name, string value)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAdminCustomValue", nameParameter, valueParameter);
        }
    
        public virtual int GetAdminCustomValue(string name, ObjectParameter returnValue)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAdminCustomValue", nameParameter, returnValue);
        }
    }
}
