//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IrmaCapaPlan
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Owners { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string Attachments { get; set; }
        public Nullable<int> RigId { get; set; }
        public string SiteId { get; set; }
    }
}
