//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IrmaCapa
    {
        public int Id { get; set; }
        public string Source { get; set; }
        public string Status { get; set; }
        public Nullable<int> Criticality { get; set; }
        public Nullable<int> ActionType { get; set; }
        public Nullable<int> ControlHierarchy { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> Topic { get; set; }
        public Nullable<int> AssignedBy { get; set; }
        public string Rig { get; set; }
        public string Position { get; set; }
        public string AssignedTo { get; set; }
        public string ActionRequired { get; set; }
        public string CompletionDescription { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> Extension { get; set; }
        public Nullable<int> ReassignedTo { get; set; }
        public string WO { get; set; }
        public string SourceId { get; set; }
        public string SourceUrl { get; set; }
        public string SiteId { get; set; }
    }
}
