//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_PermitView
    {
        public Nullable<int> JobId { get; set; }
        public string JobTitle { get; set; }
        public int PermitId { get; set; }
        public string PermitTitle { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Action { get; set; }
        public int id1 { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> CW { get; set; }
        public Nullable<int> HW { get; set; }
        public Nullable<int> CSE { get; set; }
        public Nullable<int> EI { get; set; }
        public Nullable<int> GT { get; set; }
    }
}
