//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lock
    {
        public int id { get; set; }
        public string No { get; set; }
        public string Available { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Craft { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
    }
}
