//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_JobcodeProfile
    {
        public long Id { get; set; }
        public long RigId { get; set; }
        public string JobCode { get; set; }
        public string JobTitle { get; set; }
        public Nullable<long> IADCPosition { get; set; }
        public Nullable<long> RigDepartment { get; set; }
        public Nullable<bool> HOD { get; set; }
        public Nullable<bool> Accessor { get; set; }
        public string SiteId { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Department { get; set; }
    }
}
