//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_JobCode
    {
        public int Id { get; set; }
        public Nullable<int> RigId { get; set; }
        public string JobCode { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<bool> IsHod { get; set; }
        public Nullable<bool> IsAssessor { get; set; }
        public Nullable<bool> Status { get; set; }
        public string SiteId { get; set; }
    }
}
