//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_ChangeHistory
    {
        public int Id { get; set; }
        public int RigId { get; set; }
        public string Module { get; set; }
        public string Type { get; set; }
        public string OldValues { get; set; }
        public string NewValues { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string SiteId { get; set; }
    }
}
