//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Users
    {
        public int Id { get; set; }
        public int RigId { get; set; }
        public string Passport { get; set; }
        public int UserType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> BusinessUnit { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> PSPositionId { get; set; }
        public string PSJobCode { get; set; }
        public string PSPosition { get; set; }
        public Nullable<int> PSDepartment { get; set; }
        public int Status { get; set; }
        public Nullable<int> Manager { get; set; }
        public string Password { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Country { get; set; }
        public string PostalCode { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<bool> ADUser { get; set; }
        public Nullable<bool> RequirePasswordChange { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string PersonalEmail { get; set; }
        public string ContactInfoComment { get; set; }
        public string EmergencyContactFirstName { get; set; }
        public string EmergencyContactLastName { get; set; }
        public Nullable<int> EmergencyContactRelationship { get; set; }
        public string EmergencyContactEmail { get; set; }
        public string EmergencyContactPrimaryPhone { get; set; }
        public string EmergencyContactSecondaryPhone { get; set; }
        public string EmergencyContactComment { get; set; }
        public Nullable<int> ValidatedBy { get; set; }
        public Nullable<System.DateTime> ValidatedDate { get; set; }
        public string SiteId { get; set; }
        public string BU { get; set; }
        public string Rig { get; set; }
        public string ISNNumber { get; set; }
        public string PositionName { get; set; }
        public Nullable<System.DateTime> TimeAtPosition { get; set; }
        public Nullable<System.DateTime> TimeAtRig { get; set; }
        public Nullable<System.DateTime> TimeAtEnsco { get; set; }
    }
}
