//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Scheduler
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int JobType { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ScheduleIntervalType { get; set; }
        public Nullable<System.DateTime> ScheduleTime { get; set; }
        public Nullable<System.DateTime> LastProcessedTime { get; set; }
        public string SiteId { get; set; }
    }
}
