//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_LocationMapping
    {
        public int Id { get; set; }
        public Nullable<int> EnscoLocationId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> RigId { get; set; }
        public string SiteId { get; set; }
    }
}
