//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Approvals
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public int Sequence { get; set; }
        public string Name { get; set; }
        public int RequestItemId { get; set; }
        public int Requester { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public string RequestInfo { get; set; }
        public Nullable<int> Approver { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApproverComments { get; set; }
        public Nullable<int> Status { get; set; }
        public string RequesterComments { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> Position { get; set; }
        public string SiteId { get; set; }
    }
}
