//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_UserNotCrewOnboardLookupVIew
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string WasOnRig { get; set; }
        public string OnCrewChange { get; set; }
        public string Passport { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public string Department { get; set; }
        public string Manager { get; set; }
        public string Nationality { get; set; }
        public string Email { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
