//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Rig
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> AssetTypeId { get; set; }
        public string ISM { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> BuId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Code { get; set; }
        public string PassportCode { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> MaxPOB { get; set; }
        public int Status { get; set; }
        public string SiteId { get; set; }
    }
}
