//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_RigAssetRelation
    {
        public int Id { get; set; }
        public int RigId { get; set; }
        public int Room { get; set; }
        public int Bed { get; set; }
        public int MusterStation1 { get; set; }
        public int MusterStation2 { get; set; }
        public int PrimaryLifeBoat { get; set; }
        public int SecondaryLifeBoat { get; set; }
        public string SiteId { get; set; }
    }
}
