//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_CorpPersonnelRelation
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int BusinessUnit { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Role { get; set; }
        public string SiteId { get; set; }
    }
}
