//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAP_LessonsLearnedOriginators
    {
        public int Id { get; set; }
        public Nullable<int> RigFacility { get; set; }
        public int PassportId { get; set; }
        public int LessonId { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        public virtual OAP_LessonsLearned OAP_LessonsLearned { get; set; }
    }
}
