//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAP_LessonsLearned
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OAP_LessonsLearned()
        {
            this.OAP_LessonsLearnedOriginators = new HashSet<OAP_LessonsLearnedOriginators>();
        }
    
        public int Id { get; set; }
        public string AuditId { get; set; }
        public string AuditDescription { get; set; }
        public string OapType { get; set; }
        public Nullable<System.DateTimeOffset> DateStarted { get; set; }
        public Nullable<System.DateTimeOffset> DateCompleted { get; set; }
        public string Status { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> SourceBU { get; set; }
        public Nullable<int> SourceRigFacility { get; set; }
        public string SourceForm { get; set; }
        public Nullable<int> SourceFormId { get; set; }
        public string SourceFormURL { get; set; }
        public string ImpactLevel { get; set; }
        public string eMocId { get; set; }
        public string eMocStatus { get; set; }
        public Nullable<int> Topic { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        public virtual OAP_LessonsLearnedType OAP_LessonsLearnedType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OAP_LessonsLearnedOriginators> OAP_LessonsLearnedOriginators { get; set; }
    }
}
