//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAP_Review
    {
        public int Id { get; set; }
        public Nullable<int> RigId { get; set; }
        public string SourceForm { get; set; }
        public string SourceFormId { get; set; }
        public Nullable<System.DateTimeOffset> ReviewDate { get; set; }
        public Nullable<int> CAPAId { get; set; }
        public string Comment { get; set; }
        public int ReviewerPassportId { get; set; }
        public Nullable<int> SourceBU { get; set; }
        public int RequestedBy { get; set; }
        public Nullable<System.DateTimeOffset> DateCreated { get; set; }
    }
}
