//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAP_Comment
    {
        public int Id { get; set; }
        public string SourceForm { get; set; }
        public string SourceFormId { get; set; }
        public int CommenterPassport { get; set; }
        public Nullable<System.DateTimeOffset> CommentDate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Rig { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string QuestionId { get; set; }
        public string QuestionText { get; set; }
    }
}
