//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POB_SummaryOtherView
    {
        public int Id { get; set; }
        public Nullable<int> BedsOccupied { get; set; }
        public Nullable<int> EsstentialYes { get; set; }
        public Nullable<int> EsstentialNo { get; set; }
        public Nullable<int> ShortServiceYes { get; set; }
        public Nullable<int> ShortServiceNo { get; set; }
    }
}
