//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POB_CrewSearchView
    {
        public int Id { get; set; }
        public Nullable<int> CrewChangeId { get; set; }
        public int CrewFlightId { get; set; }
        public string CrewChange { get; set; }
        public string Flight { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Name { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
