//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POB_RigPersonnel
    {
        public int Id { get; set; }
        public int PassportId { get; set; }
        public Nullable<int> CrewChangeId { get; set; }
        public Nullable<int> CrewFlightId { get; set; }
        public Nullable<int> CrewPobId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PersonnelType { get; set; }
        public Nullable<bool> ShortService { get; set; }
        public Nullable<bool> Essential { get; set; }
        public string VantageNumber { get; set; }
        public Nullable<int> Crew { get; set; }
        public Nullable<int> Tour { get; set; }
        public Nullable<int> Room { get; set; }
        public Nullable<int> Bed { get; set; }
        public Nullable<int> MusterStation1 { get; set; }
        public Nullable<int> MusterStation2 { get; set; }
        public Nullable<int> PrimaryLifeBoat { get; set; }
        public Nullable<int> SecondaryLifeBoat { get; set; }
        public string HomeAirport { get; set; }
        public Nullable<double> BodyWeight { get; set; }
        public Nullable<double> BagWeight { get; set; }
        public Nullable<short> Bags { get; set; }
        public string AirlineFlight { get; set; }
        public string Location { get; set; }
        public string Terminal { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> DateEstimatedLeave { get; set; }
        public string Optional1 { get; set; }
        public string Optional2 { get; set; }
        public string Optional3 { get; set; }
        public string Optional4 { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> PassportIssuer { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> PassportExpires { get; set; }
        public string VisaNumber { get; set; }
        public Nullable<System.DateTime> VisaExpires { get; set; }
        public Nullable<int> IdentificationIssuer { get; set; }
        public string Identification { get; set; }
        public Nullable<System.DateTime> IdentificationExpires { get; set; }
        public string Comment { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleColor { get; set; }
        public string VehiclePlateIssuer { get; set; }
        public string VehiclePlateNumber { get; set; }
        public string VehicleLocation { get; set; }
        public string VehicleComment { get; set; }
        public string WorkBoots { get; set; }
        public string RubberBoots { get; set; }
        public string Gloves { get; set; }
        public string TShirt { get; set; }
        public string CoverallTan { get; set; }
        public string CoverallFRC { get; set; }
        public string CoverallChemical { get; set; }
        public string CoverallWinter { get; set; }
        public string PPEComment { get; set; }
        public Nullable<int> LockerNumber { get; set; }
        public string ISNNumber { get; set; }
        public Nullable<int> RotationSchedule { get; set; }
        public Nullable<int> UsualRoom { get; set; }
        public Nullable<int> UsualBed { get; set; }
        public Nullable<int> SharedAccountId { get; set; }
        public string SiteId { get; set; }
    }
}
