//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POB_EmergencyTeamMembers
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public int Passport { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string SiteId { get; set; }
    }
}
