//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POB_SummaryByCompanyTypeView
    {
        public int Id { get; set; }
        public string CompanyType { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public string Nationality { get; set; }
        public string Tour { get; set; }
        public string Cabin { get; set; }
        public string LifeBoat { get; set; }
        public Nullable<System.DateTime> On { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public Nullable<bool> Ess { get; set; }
        public string Van { get; set; }
    }
}
