//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POB_TourMangementView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Crew { get; set; }
        public Nullable<int> Tour { get; set; }
    }
}
