//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POB_CrewChange
    {
        public int Id { get; set; }
        public int RigId { get; set; }
        public string Title { get; set; }
        public System.DateTime DateCrewChange { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> InboundCrew { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public string SiteId { get; set; }
    }
}
