//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POB_BatchOnboardView
    {
        public int Id { get; set; }
        public int CrewChangeId { get; set; }
        public int CrewFlightId { get; set; }
        public int PassportId { get; set; }
        public string Passport { get; set; }
        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Department { get; set; }
        public int CompanyType { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    }
}
