//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POB_BatchOffboardView
    {
        public int CrewChangeId { get; set; }
        public int CrewFlightId { get; set; }
        public int CrewPobId { get; set; }
        public int Id { get; set; }
        public int PassportId { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> Tour { get; set; }
        public Nullable<int> Crew { get; set; }
        public Nullable<int> Room { get; set; }
        public Nullable<int> Bed { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
    }
}
