//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POB_FlightManifestUnassigned
    {
        public int Id { get; set; }
        public int RigId { get; set; }
        public Nullable<int> CrewChangeId { get; set; }
        public string Number { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> ScheduledTime { get; set; }
        public Nullable<int> MaxPeople { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
