//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PobTeam
    {
        public int PobId { get; set; }
        public int TeamId { get; set; }
        public System.DateTime dt { get; set; }
        public int Id { get; set; }
    }
}
