//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int Id { get; set; }
        public string SourceForm { get; set; }
        public string SourceFormId { get; set; }
        public int AssigneeUserId { get; set; }
        public string SourceFormURL { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTimeOffset> AssignedAt { get; set; }
        public Nullable<int> AssignedBy { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AlertDate { get; set; }
    }
}
