//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CapaPlanExecution
    {
        public int Id { get; set; }
        public string ActionRequired { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string SourceUrl { get; set; }
        public string SourceId { get; set; }
    }
}
