//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Capa
    {
        public int id { get; set; }
        public string Criticality { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Action_Required { get; set; }
        public string Status { get; set; }
        public int id1 { get; set; }
        public string assigneeUserId { get; set; }
        public string AssignorUserId { get; set; }
    }
}
