//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EiIsolation
    {
        public string Source { get; set; }
        public Nullable<int> id { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public int id1 { get; set; }
    }
}
