//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OpenCap
    {
        public int Id { get; set; }
        public string Rig { get; set; }
        public string Position { get; set; }
        public string Competency { get; set; }
        public string KSA { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string AssessedBy { get; set; }
        public string Assessment { get; set; }
        public Nullable<System.DateTime> AssessedDate { get; set; }
        public string EnscoPassportNo { get; set; }
        public string SourceUrl { get; set; }
    }
}
