//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Irma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WiLocal
    {
        public int id { get; set; }
        public string Createdby { get; set; }
        public string Revisedby { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
        public string Status { get; set; }
        public string LocalPrecautions { get; set; }
        public Nullable<int> WiId { get; set; }
        public Nullable<int> RigId { get; set; }
        public Nullable<bool> ActionRequired { get; set; }
        public string WiNo { get; set; }
        public byte[] r { get; set; }
    }
}
