//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Moc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionReview
    {
        public int Id { get; set; }
        public int ActionId { get; set; }
        public int Reviewer { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public string Comments { get; set; }
    
        public virtual Action Action { get; set; }
    }
}
