//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Moc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approval
    {
        public int Id { get; set; }
        public int MocId { get; set; }
        public int Type { get; set; }
        public int UserId { get; set; }
        public int Sequence { get; set; }
        public int Status { get; set; }
        public string Comments { get; set; }
        public string ApproverNotes { get; set; }
        public string ApprovalActions { get; set; }
        public System.DateTime DateDue { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
    
        public virtual Moc Moc { get; set; }
    }
}
