//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Moc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public int LinkId { get; set; }
        public int Sequence { get; set; }
        public string Name { get; set; }
        public string HyperLink { get; set; }
        public int UploadedBy { get; set; }
        public System.DateTime UploadedDate { get; set; }
    }
}
