//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Moc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barrier
    {
        public int Id { get; set; }
        public int HazardId { get; set; }
        public int Sequence { get; set; }
        public Nullable<int> HeirarchyType { get; set; }
        public string Barrier1 { get; set; }
    
        public virtual Hazard Hazard { get; set; }
    }
}
