//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Moc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public int DocumentChangeId { get; set; }
        public string Title { get; set; }
        public string ControlNumber { get; set; }
        public int Type { get; set; }
        public int ChangeType { get; set; }
        public int Owner { get; set; }
    
        public virtual DocumentChange DocumentChange { get; set; }
    }
}
