//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Moc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Moc()
        {
            this.Actions = new HashSet<Action>();
            this.Activities = new HashSet<Activity>();
            this.Approvals = new HashSet<Approval>();
            this.ClientInterfaceChanges = new HashSet<ClientInterfaceChange>();
            this.DeviationFromStandards = new HashSet<DeviationFromStandard>();
            this.DocumentChanges = new HashSet<DocumentChange>();
            this.Notifications = new HashSet<Notification>();
            this.OrgStructureChanges = new HashSet<OrgStructureChange>();
            this.PersonnelChanges = new HashSet<PersonnelChange>();
            this.RegulatoryChanges = new HashSet<RegulatoryChange>();
            this.RigModifications = new HashSet<RigModification>();
            this.Risks = new HashSet<Risk>();
        }
    
        public int Id { get; set; }
        public string MocNumber { get; set; }
        public int Type { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public bool RiskAssessmentOnly { get; set; }
        public bool TemporaryChange { get; set; }
        public int CreatedBy { get; set; }
        public int AssignedTo { get; set; }
        public int Location { get; set; }
        public bool RequireReview { get; set; }
        public bool RequireApproval { get; set; }
        public Nullable<int> Priority { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
        public Nullable<System.DateTime> DateEffective { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public bool EamsCreated { get; set; }
        public bool EamsUpdated { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> HighestRiskLevel { get; set; }
        public Nullable<int> NotifyTeamId { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public string NonEnscoAssessors { get; set; }
        public Nullable<int> DeviationFromStandard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Actions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Approval> Approvals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientInterfaceChange> ClientInterfaceChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviationFromStandard> DeviationFromStandards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentChange> DocumentChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgStructureChange> OrgStructureChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonnelChange> PersonnelChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegulatoryChange> RegulatoryChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigModification> RigModifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Risk> Risks { get; set; }
    }
}
