//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Moc.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnscoMocEntities : DbContext
    {
        public EnscoMocEntities()
            : base("name=EnscoMocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionNotification> ActionNotifications { get; set; }
        public virtual DbSet<ActionReview> ActionReviews { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Approval> Approvals { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<Barrier> Barriers { get; set; }
        public virtual DbSet<ClientInterfaceChange> ClientInterfaceChanges { get; set; }
        public virtual DbSet<DeviationFromStandard> DeviationFromStandards { get; set; }
        public virtual DbSet<DocumentChange> DocumentChanges { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Hazard> Hazards { get; set; }
        public virtual DbSet<Moc> Mocs { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<OrgStructureChange> OrgStructureChanges { get; set; }
        public virtual DbSet<PersonnelChange> PersonnelChanges { get; set; }
        public virtual DbSet<RegulatoryChange> RegulatoryChanges { get; set; }
        public virtual DbSet<RigModification> RigModifications { get; set; }
        public virtual DbSet<Risk> Risks { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<XLookupAdmGroup> XLookupAdmGroups { get; set; }
        public virtual DbSet<XLookupAdmSubSystem> XLookupAdmSubSystems { get; set; }
        public virtual DbSet<XLookupAdmSystem> XLookupAdmSystems { get; set; }
        public virtual DbSet<XLookupControlHeirarchy> XLookupControlHeirarchies { get; set; }
        public virtual DbSet<XLookupCriticality> XLookupCriticalities { get; set; }
        public virtual DbSet<XLookupMocType> XLookupMocTypes { get; set; }
        public virtual DbSet<XLookupPriority> XLookupPriorities { get; set; }
        public virtual DbSet<XLookupRigModDiscipline> XLookupRigModDisciplines { get; set; }
        public virtual DbSet<XLookupRigModReason> XLookupRigModReasons { get; set; }
        public virtual DbSet<XLookupRiskConsequence> XLookupRiskConsequences { get; set; }
        public virtual DbSet<XLookupRiskProbability> XLookupRiskProbabilities { get; set; }
        public virtual DbSet<XLookupRiskSeverity> XLookupRiskSeverities { get; set; }
        public virtual DbSet<XLookupStatu> XLookupStatus { get; set; }
    }
}
