//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Moc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonnelChange
    {
        public int Id { get; set; }
        public int MocId { get; set; }
        public int UserId { get; set; }
        public bool OnlyHitch { get; set; }
        public Nullable<int> PreviousPosition { get; set; }
        public Nullable<int> NewPosition { get; set; }
        public Nullable<int> PositionType { get; set; }
        public Nullable<int> PreviousLocation { get; set; }
        public Nullable<int> NewLocation { get; set; }
        public Nullable<int> LocationType { get; set; }
    
        public virtual Moc Moc { get; set; }
    }
}
