//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensco.Moc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class XLookupAdmSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XLookupAdmSystem()
        {
            this.XLookupAdmSubSystems = new HashSet<XLookupAdmSubSystem>();
        }
    
        public int Id { get; set; }
        public int GroupId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    
        public virtual XLookupAdmGroup XLookupAdmGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XLookupAdmSubSystem> XLookupAdmSubSystems { get; set; }
    }
}
